# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcca5d6ce97ffe9d63122f87962ca614d28a0c38853d6eae75c7f1f1c1f07e3d0f37d1d2551ad58e4326f1b5190a6abf08a03112561759d78770bbcf35a993da

test:
  secret_key_base: f456e803a2e12f5ee1c0fe1ec6cf4adaac3fe112381d0c5ae698c868d3258dad57d7b5b3c1e29f3b2dfd8bda6d629448da32298a80fa1e4f102ab361c8d45c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
